# Generated by Django 5.1.2 on 2024-11-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_year', models.IntegerField()),
                ('job_title', models.CharField(max_length=255)),
                ('job_category', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare')], max_length=100)),
                ('salary_currency', models.CharField(max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_in_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_residence', models.CharField(max_length=100)),
                ('experience_level', models.CharField(choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Executive', 'Executive')], max_length=50)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=50)),
                ('work_setting', models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('company_location', models.CharField(max_length=100)),
                ('company_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50)),
            ],
        ),
    ]
